### ISSUE TITLE
example URLs should be allowed

### ISSUE THREAD

**Issue by mbeijen** [apocalypse/perl-test-pod-no404s#2]
Sometimes you need to have a URL in your documentation, because it can be a parameter for instance.

[RFC6761](http://tools.ietf.org/html/rfc6761) has reserved the example.com, example.net domains for this.

If one of these URLs is in the POD the validity should not be checked.

Would you accept a pull request that implements this?

**Comment by apocalypse** [comment]
Hello,

 I've released v0.02 which skips several example URLs as defined in the RFC. Thanks for spotting this! If I've missed something please feel free to submit a pull request :)

**Comment by mbeijen** [comment]
Thanks a lot!  I'll be able to use it in some of my modules now.

## 

Michiel

Op 2 nov. 2014 om 03:40 heeft Apocalypse <notifications@github.com<mailto:notifications@github.com>> het volgende geschreven:

Hello,

I've released v0.02 which skips several example URLs as defined in the RFC. Thanks for spotting this! If I've missed something please feel free to submit a pull request :)
